apiVersion: v1
kind: Service
metadata:
  name: kubernetes-basics-service
spec:
  selector:
    app: kubernetes-basics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer